### ISSUE TITLE
Redesign Vivaldi Snapshot/Beta

### ISSUE THREAD

**Issue by linusg** [keeferrourke/la-capitaine-icon-theme#144]
There are .deb packages for Vivaldi Beta here: https://vivaldi.com/blog/snapshots/snapshot-1-0-403-20-beta3-is-almost-here/

The icon for Vivaldi Snapshot is already present (`vivaldi-snapshot.svg`), but the same as `vivaldi.svg`. Should be more like the Chrome Beta icon:

![image](https://cloud.githubusercontent.com/assets/19366641/25374054/4f1c9514-299c-11e7-8fe8-2900bf517539.png)

**Comment by keeferrourke** [comment]
@linusg, I've simplified the original vivaldi icon to be more in line with the current logo (conveniently, it has a 45 deg shadow, just like a lot of other icons I've made!! :grin:).

See below, I will commit if you think the design is good (since I do not use the browser myself)

`vivaldi.svg` | `vivaldi-snapshot.svg`
--|--
![vivaldi](https://cloud.githubusercontent.com/assets/6888381/25686453/5c12d994-303c-11e7-974f-c26ff4097cd3.png) | ![vivaldi-snapshot](https://cloud.githubusercontent.com/assets/6888381/25686469/818463f0-303c-11e7-9c07-bf6f11751891.png)

**Comment by linusg** [comment]
You got it. Awesome!
Great work Keefer, really appreciate it. Commit can come...

**Comment by keeferrourke** [comment]
I'll push tonight :grin: files are on my other machine :roll_eyes:

**Comment by keeferrourke** [comment]
delaying to tomorrow

**Comment by keeferrourke** [comment]
Sorry for the delay! Was using a different machine than normal, hadn't really been sleeping much, and got super busy. Enjoy the new icons :)
