### ISSUE TITLE
[Request] Discord

### ISSUE THREAD

**Issue by RaitaroH** [keeferrourke/la-capitaine-icon-theme#172]
Icon name: discord.png
Context: chatting app
Icon reference:
![discord](https://user-images.githubusercontent.com/19552720/27793633-84772c0a-6007-11e7-8de9-bb4d8efab037.png)

discord.desktop content:
`[Desktop Entry]`
`Name=Discord`
`StartupWMClass=discord`
`Comment=All-in-one voice and text chat for gamers that's free, secure, and works on both your desktop and phone.`
`GenericName=Internet Messenger`
`Exec=/usr/share/discord/Discord`
`Icon=discord`
`Type=Application`
`StartupNotify=true`
`Categories=Network;InstantMessaging;`

I think you didn't notice, but I left a message for you with the svg needed and the symbolic variants here:
https://github.com/keeferrourke/la-capitaine-icon-theme/issues/114#issuecomment-312443972

**Comment by LaurentTreguier** [comment]
Hi there, I just saw this and thought that the Canary version of Discord could be done easily if the main one is done (the icon is almost the same with yellow instead of blue, and a shadow):
![discord-canary](https://user-images.githubusercontent.com/7602755/28743829-86987b08-744b-11e7-96ec-1bc550356b2e.png)
discord-canary.desktop content:
```
[Desktop Entry]
Name=Discord Canary
StartupWMClass=discord
Comment=All-in-one voice and text chat for gamers that's free, secure, and works on both your desktop and phone.
GenericName=Internet Messenger
Exec=/usr/share/discord-canary/DiscordCanary
Icon=discord-canary
Type=Application
StartupNotify=true
Categories=Network;InstantMessaging;
```
Using the same icon as the regular Discord and replacing blue with yellow should be pretty much all that would be needed for this.

**Comment by keeferrourke** [comment]
Haven't had a chance to look at requests for a while. I'll add these in mid-august.
