### ISSUE TITLE
Dark Status Icons...

### ISSUE THREAD

**Issue by yapr** [keeferrourke/la-capitaine-icon-theme#178]
First off,I love your icon theme....Simply fabulous!
Thank you for taking the time and effort to making this one.

Now to the issue.
The status icons for redshift and wifi appear to be darker while the battery icon fits in perfectly well..

Here are 2 scrrenshots : One where redshift is disabled and the other where redshift is enabled..
Note : In both the cases,wifi was working,and I was connected to the internet.

![screenshot_2017-08-02_23-01-14](https://user-images.githubusercontent.com/29171250/28887005-24692f4a-77d9-11e7-8b98-f26065d7231d.png)
![screenshot_2017-08-02_23-00-59](https://user-images.githubusercontent.com/29171250/28887006-2517a08e-77d9-11e7-80f2-6b266a2dbd4d.png)

As you can see,the redshift status icon remains black no matter what,and the network icon remains black,even while connected..

Desktop : XFCE
GTK Theme : Adapta
WM Theme : Adapta

Hope you fix the issue..
Thank you again for creating this fantastic icon theme..

**Comment by keeferrourke** [comment]
Have you run the configure script and selected that you have a dark panel? If not, please run the configure script.

If you have... there is a bigger issue that I don't currently have time to hunt down.

Let me know.

**Comment by yaoghu** [comment]
i did not know about the configure script at all....
but nonetheless, i ran it....
now,the wifi icon is working perfectly well....but redshift is still dark while active...

![cs56wdl](https://user-images.githubusercontent.com/29171250/28984175-3fab9110-797a-11e7-992b-1649f2291b64.png)
but....i can probably live with it tho,seeing as this is a dope ass icon set...

**Comment by keeferrourke** [comment]
@yaoghu there isn't much I can do about the battery icons... unfortunately a lot of DEs use 'full', 'good', 'low' and 'critical' statuses, rather than percentages. La Capitaine supports both kinds of reporting, but if your DE uses the quartile reporting method and chooses silly percentages at which the icon should change... you're stuck with a poor visualization. Best you can do in that situation is put the battery percentage in your top bar.

I'll revert a change I made to the red shift icons a few months ago; they used to be rendered as full colour status icons, which is probably a lot more useful visually. This probably won't happen until after exams are finished in about 1.5 weeks though.

Cheers!

**Comment by yaoghu** [comment]
no problem mate...take your time..
