### ISSUE TITLE
[Request] Kwallet Manager

### ISSUE THREAD

**Issue by now-im** [keeferrourke/la-capitaine-icon-theme#188]
### Application information

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| KWalletManager   | `org.kde.kwalletmanager5.desktop` | Application | ![kwalletmanager](https://user-images.githubusercontent.com/22009014/29488506-558da012-852e-11e7-954a-76dbfe29556e.png) |

### Desktop file

```

[Desktop Entry]
Name=KWalletManager
Comment=KDE Wallet Management Tool
GenericName=Wallet Management Tool
Exec=kwalletmanager5 %u
MimeType=application/x-kwallet;
InitialPreference=6
Icon=kwalletmanager
Type=Application
Terminal=false
StartupNotify=false
Categories=Qt;KDE;System;Security;
X-DocPath=kwallet5/index.html
X-DBUS-ServiceName=org.kde.kwalletmanager5



```

**Comment by keeferrourke** [comment]
your issue is a little confusing, since the icon in your desktop file already exists (see [kwalletmanager.svg](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/master/apps/scalable/kwalletmanager.svg)), and the icon name you specify in the table isn't an icon.

I have however updated the icon design, and added a symlink to `org.kde.kwalletmanager.svg`. Please let me know if this update solves your issue.

**Comment by now-im** [comment]
Yes the issue got fixed. There was a mistake from my side, I searched `kwallet` rather than `kwalletmanager `that resulted in no .svg file.
