### ISSUE TITLE
[Request] Icons for Plasma 5

### ISSUE THREAD

**Issue by somniumAeternam** [keeferrourke/la-capitaine-icon-theme#20]
Hi, for Plasma 5 there are some crucial icons missing:

- VCS-icons for emblems in dolphin, according to breeze icon theme (under emblems -> 16):
vcs-added.svg
vcs-conflicting.svg
vcs-locally-modified-unstaged.svg
vcs-locally-modified.svg
vcs-normal.svg
vcs-removed.svg
vcs-update-required.svg

- Update status icons (status -> 22):
update-high.svg
update-low.svg
update-none.svg
update-medium.svg

- Owncloud icons are missing (see other issues)

- Missing apps:
Kbibtex

**Comment by keeferrourke** [comment]
Great! Thanks for pointing this out to me, I'll check out the Breeze theme as reference and hopefully push an update for this soon.

**Comment by somniumAeternam** [comment]
Maybe you should think about providing two different versions of your icon theme, one for gnome and one for plasma. You can use the plasma5 branch from my fork. It includes all the missing icons so far.  What do you think?

**Comment by keeferrourke** [comment]
I'd rather keep one universal version of La Capitaine if at all possible, and just modify symlinks via the configuration script. I realise this may not be the most elegant solution, but it's much easier to maintain on my end, and also keeps the versioning simple and reduces fragmentation of the icon theme through having multiple branches and versions.

I want to merge some of your changes to testing at some point, but this might take a while due to how busy I am this summer. I'll get to it when I have some free time.

Here's what I suggest:

 1. Submit a pull request for the *new* icons that you've created that are required for Plasma5. 
 2. Any icons that you've modified to work better with Plasma5, name them with the following convention: `*-plasma5.svg`. Submit another  pull request with these icons.
 3. I'll play with Plasma5 for a bit and this will then allow me to add an option for the Plasma5 desktop in the config script. The updated script will take care of renaming and replacing icons appropriately if the users' system indicates that Plasma5 is their preferred environment.

**Comment by somniumAeternam** [comment]
Ok, this sound reasonably. I will also assume that the plasma5 theme will be completely light. So also the panel will be light. That means, that e.g. the owncloud status icons will be dark grey.

A completely dark theme would require far more changes to the whole theme, so this is not the top priority.

**Comment by keeferrourke** [comment]
Sounds about right! And yes... I need to fix the owncloud status icons to make them grey. That was just an error in my thinking before. Late nights man :P

I would like to have a dark theme available in the near future; I think that would just be a matter of programmatically recolouring all the status and action icons. Maybe check back in a few weeks and I might have something in the works. I'm currently out of country, so not working or pushing as often as I usually do.

**Comment by keeferrourke** [comment]
Closing since I've merged in required changes from #28 and made additional changes in #30
