### ISSUE TITLE
Icon Request: Slack

### ISSUE THREAD

**Issue by bilelmoussaoui** [keeferrourke/la-capitaine-icon-theme#216]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Slack | `slack` | `slack.desktop` | ![Slack](http://i.imgur.com/pALbszn.png)| la-capitaine-icon-theme |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by linusg** [comment]
The "original icon" isn't the same anymore: [Slack changed their logo](https://slackhq.com/say-hello-new-logo).

![image](https://user-images.githubusercontent.com/19366641/51445488-cfcef680-1d05-11e9-8ee0-70849f781281.png)

Many don't like it (including me), but that's a different story...

**Comment by keeferrourke** [comment]
Deviates a bit from the "aubergine" rounded circle look, but hopefully this makes people happy.
Initially didn't theme the previous icon because it didn't look out of place in La Capitaine, and attempts to modify it were unsuccessful.

As much as the new logo is "interesting," it's much more malleable from a design perspective, so I'm happier with it ;)

**Comment by keeferrourke** [comment]
@linusg It's a bit arbitrary, but if the app is strictly (or primarily) messaging, I go with the round bubble icon. If it's mixed media (like Twitter, Discord) I'll go with the square bubble (looks more like a "post" to me), and other shapes if I can't really make the branding work. Some of these I didn't design, i.e. they were contributed by other authors and looked nice enough.

I'd like to make things a bit more consistent though, so this is a good point to think of! :)
