### ISSUE TITLE
Applications installed with snap aren't themed.

### ISSUE THREAD

**Issue by cairinmichie** [keeferrourke/la-capitaine-icon-theme#254]
Snap installs the theme files for applications in `~/snap/application_name/application_number/.local/share/icons`
![Screenshot from 2017-10-25 11-16-38.png…]()

None of the applications loaded through snap have the custom icons.

**Comment by cairinmichie** [comment]
I am using Ubuntu 17.10 (Gnome 3.26.1) if it makes any difference.

**Comment by keeferrourke** [comment]
This is not a useful issue. Open issues for unthemed snap packages individually, as per the guidelines in the Wiki.

Please read this document in its entirety: https://github.com/keeferrourke/la-capitaine-icon-theme/wiki/Submitting-New-Issues

**Comment by cairinmichie** [comment]
@keeferrourke I think you miss-understood my issue.

The packages are themed if I install them with apt-get, gdebi etc. but not snap.
For example the atom icon in the screenshot isn't themed because it's installed with snap. But if you install it with the .deb file from the atom github repo it is themed.

**Comment by cairinmichie** [comment]
Also, it's like that with all the snap packages that can be installed through snap. So I made this issue so that you could do a check for snap when installing. Because the artwork is already made..

**Comment by keeferrourke** [comment]
I think you misunderstand the problem.

Snap packages are containerized and treated completely differently than regular deb packages. To this point, I am not even sure if they can they can be themed without manually modifying your system due to the way Snaps are treated. You'll need to provide copies of the desktop files for each of your unthemed snaps, just like a regular issue.

If Snaps are at all like Flatpaks (I do not run Ubuntu FYI), then a desktop should be installed to a directory such as `~/snap/application_name/application_number/.local/share/applications`. Each of these desktop files will specify application icon names. I will need these applications icon names.

*I cannot fix what I do not know is broken*.
