### ISSUE TITLE
[Request] Add 2048 and gnash-player icons

### ISSUE THREAD

**Issue by sarether** [keeferrourke/la-capitaine-icon-theme#33]
2048 (game) & gnash-player icons.
File-manager icon (non mac like) variants (?) please.

**Comment by keeferrourke** [comment]
Please follow the guidelines for submitting icon requests in the readme. I'm going to need the `Icon=        ` line from the relevant application .desktop file.

Desktop files are usually found in `/usr/share/applications/`

If you can, please post references for icon designs as well.

**Comment by keeferrourke** [comment]
@sarether There is already a 2048 icon in La Capitaine, so it may be named incorrectly for your system. I'm going to need more information from you so I make the relevant symlinks.

**Comment by sarether** [comment]
File-managers names is "system-file-manager", obviously.
>2048 (game)
The name is "gnome-2048".
All other icon themes  show their own 2048 icons well.

**Comment by keeferrourke** [comment]
See https://github.com/keeferrourke/la-capitaine-icon-theme/commit/dcdd8a7e406ff9de5ae4c57a5baea786d56e2bf2 for the fix for the 2048 icon.

A Gnash icon is in the works. 

Since the file manager icon variants is a significantly different issue than that of a simple request for new icons, I've created #34 to deal with it.

**Comment by keeferrourke** [comment]
Added gnash icon in 833a8d1
