### ISSUE TITLE
different look in nautilus' icon view and the icon shown in properties window

### ISSUE THREAD

**Issue by handrake0724** [keeferrourke/la-capitaine-icon-theme#40]
As shown below figure, the icon shown in nautilus and the icon shown in properties window does not match each other. I don't know how to fix this behavior.
FYI, I am using arch linux with gnome 3.2 + gtk3 3.2 + cinnamon 3.0.

![selection_001](https://cloud.githubusercontent.com/assets/18005991/18717572/44f66262-805b-11e6-9257-c54b18bd4023.png)

**Comment by keeferrourke** [comment]
I do not believe this is an issue with La Capitaine, but rather the way Nautilus assigns the icons to the files. Keep in mind unix-like systems don't care about file extensions, so if your file content doesn't match what you expect, then the wrong mimetype might be detected.

Closing this because there is nothing I can do about it. If something suggests to me otherwise, I'll reconsider.
