### ISSUE TITLE
Some icons show up too big in dialogue boxes

### ISSUE THREAD

**Issue by CreativeUsern** [keeferrourke/la-capitaine-icon-theme#41]
When picking things in dialogue boxes, Sometimes certain icons show up as really big.  I'm on xfce.
![](https://cloud.githubusercontent.com/assets/21045097/18976081/f2e297e8-8663-11e6-9035-007a60d97dca.png)

**Comment by keeferrourke** [comment]
wow, that is insane o.O
I've had no such problems like that under XFCE before, but I am aware that some of the SVGs are immensely too big. I'll look into this, but it's going to take a while to fix since it means I literally have to go through every folder/app icon and make sure none are bigger than 48x48.

honestly I fault certain desktop environments for not knowing how to scale SVGs properly... but *c'est la vie*. Fix will be on it's way soonish.

**Comment by keeferrourke** [comment]
This should, to my knowledge be fixed by now. If there are wrongly sized icons, please feel free to reopen this.
