### ISSUE TITLE
[REQUEST] - XFCE system try icons

### ISSUE THREAD

**Issue by rtalexk** [keeferrourke/la-capitaine-icon-theme#52]
I love Le Capitaine icon theme, I use it on all my Linux distros, I tend to use Plasma 5 and Xfce but always i have the same problem: system tray.

I tried to configure by myself, but symbolic links already exists. I'm think hicolor icons are ugly.

I don't know how Xfce manage icons, maybe something like #35 could help.

![captura de pantalla_2016-11-06_10-05-41](https://cloud.githubusercontent.com/assets/16341644/20039870/6e0639d0-a409-11e6-874d-f1fc873dc0f1.png)

**Comment by juanlatorre** [comment]
Indeed, i request this too, this icons are perfect !

**Comment by keeferrourke** [comment]
Dammit. I thought I fixed this. I'll look into it -- but I'm in the middle of my second round of midterms (they never end!!)

if anyone else has a chance to look at this, I'd be more than happy for the help :)

**Comment by juanlatorre** [comment]
Hey, i've look into this, for some reason my icons work fine after deleting the "xfpm-primary*" icons from Hicolor theme, the icons from La Capitaine worked perfectly (i edited some of them to match my dark panel). 

Inside the XFCE-Power-Managament plugin for XFCE4-Panel in /usr/share/xfce4/panel/plugins/power-manager-plugin.desktop, there is a String that say:

Icon=xfpm-primary-100-charging

![screenshot_2016-11-08_09-59-39](https://cloud.githubusercontent.com/assets/4494526/20100067/656b023c-a59a-11e6-90eb-f7b3111ebf70.png)

I believe that the XFPM module isn't finding the icon on La Capitaine pack and that's why is using de Hicolor icons, maybe the icons need the same name (I renamed my icons and now work, but i don't know if is because of the rename).

Sorry for my bad english, and i hope that this can be helpful for you.

**Comment by keeferrourke** [comment]
hmm okay, so I think the battery icons XFCE is looking for are called `xfpm-primary-*` and not `xfpm-battery-*`.

I can get an update pushed by thursday, if it's not up by then - just ping me.

Cheers.

**Comment by juanlatorre** [comment]
Thanks, i'll be in touch !

**Comment by ryzokuken** [comment]
What's the status on this? I am facing the same problem (all icons are rendered perfectly, but the power icons looks ugly as hell) this issue does not occur when I use Numix or Paper (if it helps)

**Comment by keeferrourke** [comment]
Hi @ryzokuken I saw the issue you opened. This has fallen by the wayside for a while because I've been busy. I'll try to take a look this week, but I'm super busy with school assignments right now. As mentioned before, it's likely that I just need to add symlinks with names of the pattern `xfpm-primary-*`. I don't currently have XFCE set up though, so I cannot test this right now.

**Comment by ryzokuken** [comment]
@keeferrourke If it involves only symlinking, I could submit a PR if you could give me a little more detail about what to do (if you are too busy to do it). Also, I could help you test it if you'd like. Keep up the good work.

**Comment by keeferrourke** [comment]
I *think* every `xfpm-battery-*` icon needs to be symlinked to an `xfpm-primary-*` with the same suffix. For example:
 * `ln -s xfpm-battery-000-charging.svg xfpm-primary-000-charging.svg`
 * `ln -s xfpm-battery-caution.svg xfpm-primary-000-caution.svg`
 * etc.

A PR + testing would be welcome, thanks!

**Comment by keeferrourke** [comment]
Should be fixed in the latest commits. See issue #119.
