### ISSUE TITLE
Can't find the configuration script

### ISSUE THREAD

**Issue by Dyrimon** [keeferrourke/la-capitaine-icon-theme#584]
Hi, I wanted to run the configuration script to use the dark mode. However, when I looked for the script in `/usr/share/icons/La-Capitaine` I couldn't find it. There is no `./configure` in there.

I'm using Fedora 33 with Cinnamon desktop and I installed La-Capitaine from the repository. Is it different with the repository version from the cloned version?

**Comment by Dyrimon** [comment]
P.S: I didn't add the copr, just the standard repository version.

**Comment by darkshram** [comment]
@Dyrimon: Configure scripts and make files are always excluded in RPM packages. You need to download the sources from here to make changes and install under ~/.icons/:

```
mkdir -p ~/.icons/
cd ~/.icons/
git clone https://github.com/keeferrourke/la-capitaine-icon-theme
cd la-capitaine-icon-theme 
./configure --any-options-you-need
```
Or download the source rpm (`dnf download --source la-capitaine-icon-theme`), install source rpm, modify spec file to fit your needs and then rebuild and install modified package. It is not an easy task for beginners. Linux distributions build packages with general/default options in most cases to fit general users' needs.

@keeferrourke: la-capitaine-icon-theme has been packaged in Fedora since April 2019 and is (AFAIK) still maintained by Artem Polishchuk.

**Comment by Dyrimon** [comment]
> It's possible the Fedora packagers didn't include the configure script in their package. Consider cloning from git!

That's a shame, I guess I'll have to pull from git to update it every time.
