### ISSUE TITLE
Some icons are missing the extension names

### ISSUE THREAD

**Issue by wangxa** [keeferrourke/la-capitaine-icon-theme#79]
For example, the file `application-vnd.ms-excel` is missing `.svg` in the git commit version of 136fdcd.

**Comment by keeferrourke** [comment]
thanks for pointing this out! I found the following files to be the only ones affected and renamed them appropriately:

In mimetypes/scalable:
 * `application-vnd.ms-excel` &rarr; `application-vnd.ms-excel.svg`
*  `application-x-xz-svg` &rarr; `application-x-xz.svg`

This has been fixed in commit 12c93b1.
